[Settings]

; "enex" means entry/ exit with the yellow cone marker

RequirementsCheck = 1    ; Only disable if you have a good reason.

OnlyRawFeatures = 0      ; This represents a simplified EHI mode. It activates the most enex regardless of game progress.
                         ; Dynamic features like interior access by story progress, Doherty Garage, movable Area 69 gates etc. won't be available.
                         ; It is automatically enabled if you're using an incompatible main.scm or if something is wrong with your game.

MarkersDrawDistX2 = 1    ; Increases markers and enex cone view distance. Same setting as in TweaksSA.

NewSaveHouses = 1        ; Adds 2 new properties to buy in Mulholland and Richman (LS)

DohertyTuning = 2        ; Mission progress that unlocks car tuning in the Doherty garage. // 0 = No Tuning.
                         ; 1 = After first mission in San Fierro. // 2 = After first Doherty side mission. // 3 = After completing all Doherty side missions.
                         ; It's automatically disabled if you have "Doherty Garage" mod installed.

DohertyBackdoor = 1      ; Makes the backdoor of the tuning garage movable

DohertyEnex = 2          ; 0 = Disable. // 1 = Enable. // 2 = Enable and move savepoint to interior. // 3 = Disable and move savepoint to interior.

DohertyWeapons = 1       ; Moves the photo reward weapon pickups inside the garage

AngelPineTrailer = 2     ; 0 = Disable. // 1 = Enable. // 2 = Enable and move savepoint to interior.
                         ; 3 = Disable and move savepoint into the trailer. (For LivelyTrailers mod)

TorenoSafeHouse = 2      ; 0 = Disable. // 1 = Enable. // 2 = Enable and move savepoint to interior.
                         ; Enabling will also move the weapon pickups of the Toreno Ranch inside the interior.

FourDragonsFlat = 1      ; Creates a save apartment inside the Four Dragon's Casino and moves horseshoe reward weapon pickups to Wuzi's room

2FloorAmmunation = 1     ; Activates an alternative Ammunation interior for the store in Market, LS

GlazedOffice = 1         ; If you fall to the ground floor after entering, increase the priority of EHI in modloader.ini

LS_Lighthouse = 1        ; Enex for lighthouse at Santa Maria Beach

LS_OperaHouse = 1        ; Roof of the opera house near the Mulholland intersection

LS_LuxuryHouses = 1      ; Balconies of some villas in Mulholland and Richman (LS)

MaddDoggMansion = 1      ; Additional enex and wardrobe in Madd Dogg's mansion

SF_Hospital = 1          ; You might wanna disable it if not using Proper Fixes


; Restaurants

Diner1 = 1
Diner2 = 1
SecretValley = 1
WorldOfCoq = 1
